name: Deploy Cloud Functions

on:
  schedule:
    # UTC
    - cron: "27 17 * * *"
  workflow_dispatch:
    inputs:
      mypy_version:
        description: mypy version
        required: true
        type: string
        default: master

permissions:
  contents: read
  id-token: write

jobs:
  gcp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: echo ${{ github.event.inputs.mypy_version }} @@@
